"""upd the tables

Revision ID: eecc414d64fe
Revises: c4a904c28b3c
Create Date: 2023-08-07 14:41:04.948145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eecc414d64fe'
down_revision = 'c4a904c28b3c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked_adverts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('advert_id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'advert_id')
    )
    op.add_column('adverts', sa.Column('creating_order', sa.Integer(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('adverts', 'creating_order')
    op.drop_table('liked_adverts')
    # ### end Alembic commands ###
